name: Step 4-4 # Update Backend Implementation

on:
  push:
    branches:
      - feature/test
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  issues: write

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.4.0

  check_step_work:
    name: Check step work
    runs-on: ubuntu-latest
    needs: [find_exercise]
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.4.0

      - name: Update comment - checking work
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/checking-work.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # START: Check practical exercise

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Check implementation
      - name: Check for if keyword in delete endpoint
        id: check-if-keyword
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: packages/backend/src/app.js
          keyphrase: 'if'
          minimum-occurrences: 1
          case-sensitive: false

      - name: Check for delete keyword in endpoint implementation
        id: check-delete-keyword-implementation
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: packages/backend/src/app.js
          keyphrase: 'delete'
          minimum-occurrences: 1
          case-sensitive: false

      # Check tests for if condition
      - name: Check for if keyword in tests
        id: check-test-if-keyword
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: packages/backend/__tests__/app.test.js
          keyphrase: 'if'
          minimum-occurrences: 1
          case-sensitive: false

      - name: Check for delete keyword in tests
        id: check-test-delete-keyword
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: packages/backend/__tests__/app.test.js
          keyphrase: 'delete'
          minimum-occurrences: 1
          case-sensitive: false

      - name: Check for test keyword in tests
        id: check-test-test-keyword
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: packages/backend/__tests__/app.test.js
          keyphrase: 'test'
          minimum-occurrences: 1
          case-sensitive: false

      # Run tests
      - name: Run backend tests
        id: run-backend-tests
        continue-on-error: true
        run: |
          cd packages/backend
          npm test
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Backend tests failed to run successfully"
            exit 1
          fi
          exit 0

      - name: Build message - step results
        id: build-message-step-results
        uses: skills/action-text-variables@v2
        with:
          template-file: exercise-toolkit/markdown-templates/step-feedback/step-results-table.md
          template-vars: |
            step_number: 4-4
            passed: ${{ !contains(steps.*.outcome, 'failure') }}
            results_table:
              - description: "Backend app.js should contain an if statement"
                passed: ${{ steps.check-if-keyword.outcome == 'success' }}
              - description: "Backend app.js should contain a delete endpoint"
                passed: ${{ steps.check-delete-keyword-implementation.outcome == 'success' }}
              - description: "Backend tests should include tests for delete functionality"
                passed: ${{ steps.check-test-delete-keyword.outcome == 'success' }}
              - description: "Backend tests should include tests for if condition in delete functionality"
                passed: ${{ steps.check-test-if-keyword.outcome == 'success' }}
              - description: "Backend tests should include tests for delete functionality"
                passed: ${{ steps.check-test-test-keyword.outcome == 'success' }}
              - description: "Backend tests should run successfully without errors"
                passed: ${{ steps.run-backend-tests.outcome == 'success' }}

      - name: Create comment - step results
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "$COMMENT_BODY" \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ steps.build-message-step-results.outputs.updated-text }}

      - name: Debug step outcomes
        run: |
          echo "Overall result: ${{ contains(steps.*.outcome, 'failure') && 'FAILURE' || 'SUCCESS' }}"
          echo ""
          echo "Failed steps (if any):"
          echo '${{ toJSON(steps) }}' | jq -r 'to_entries[] | select(.value.outcome == "failure") | "❌ \(.key)"' || echo "No failures detected"

      - name: Fail job if not all checks passed
        if: contains(steps.*.outcome, 'failure')
        run: exit 1

      # END: Check practical exercise

      - name: Build message - step finished
        id: build-message-step-finish
        uses: skills/action-text-variables@v2
        with:
          template-file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
          template-vars: |
            next_step_number: 4-5

      - name: Update comment - step finished
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "$ISSUE_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY: ${{ steps.build-message-step-finish.outputs.updated-text }}

  post_next_step_content:
    name: Post next step content
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.4.0

      - name: Create comment - add step content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file ".github/steps/4-5-bulk-add-unit-test.md"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create comment - watching for progress
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Disable current workflow and enable next one
        run: |
          gh workflow disable "Step 4-4"
          gh workflow enable "Step 4-5"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}